Classes and Structures for ARP packet counters
ntop/ntopng pull request #2394
Opened 2019-02-17 21:36 UTC by FrancescoStaccini

Hash table of ARP packet counters, that represent the number of packet sent/received from/to specific devices.

(not finished yet)

2019-02-18 18:16 UTC, simonemainardi requested changes

2019-02-18 18:16 UTC, simonemainardi commented on src/NetworkInterface.cpp
> +  u_int8_t src_mac[6];
never used?

2019-02-18 18:16 UTC, simonemainardi commented on src/NetworkInterface.cpp
> +  u_int8_t dst_mac[6];
never used?

2019-02-18 18:16 UTC, simonemainardi commented on src/NetworkInterface.cpp
> +  if( (info->elem == NULL) && !info->elem->equal(e->getSourceMac(), e->getDestinationMac()) ){
code inside this is IF is never reached and is going to crash with a SEGFAULT when info->elem is null

2019-02-18 18:16 UTC, simonemainardi commented on src/NetworkInterface.cpp
> +  disablePurge(false);
enable / disable purge not necessary

2019-02-18 18:16 UTC, simonemainardi commented on src/NetworkInterface.cpp
> +        arp_hash_matrix->add(ret);
not handled the case when this add fails: must delete and free ret

2019-02-18 18:16 UTC, simonemainardi commented on src/NetworkInterface.cpp
> +    e->AddOneSentRequests();
please use the ntopng convention and name this kind of methods similar to incSentArpRequests(), incRcvdArpRequuests() etc..

2019-02-18 18:16 UTC, simonemainardi commented on src/ArpStatsMatrixElement.cpp
> +    if(  memcmp(src_mac, _src_mac, 6) == 0 && memcmp(dst_mac, _dst_mac, 6) == 0 )
please remove unnecessary spaces

2019-02-18 18:16 UTC, simonemainardi commented on src/NetworkInterface.cpp
> +            ntop->getPrefs()->get_max_num_hosts());
this maximum may not be enough as this is a matrix

2019-02-19 09:43 UTC, FrancescoStaccini commented
thanks a lot @simonemainardi  for the review. I will apply the changes and follow the suggestions.

2019-03-05 08:45 UTC, simonemainardi commented
@FrancescoStaccini are you having troubles in pushing the new version with the suggested changes? I'can see it, it's seems the commit from 1 day ago involves a pull request from 2015...

![image](https://user-images.githubusercontent.com/3397663/53792177-598bf980-3f2b-11e9-8d49-3ce2bfbe76b7.png)

2019-03-05 09:06 UTC, FrancescoStaccini commented
I hope I did not messed up, i was trying to sync my fork with ntop

2019-03-05 15:49 UTC, lucaderi commented
Cleanup and restart

2019-03-05 15:49 UTC, closed without merging