Fix L7 Protocol usage & empty table statement using the view interface in Server Ports Analysis page
ntop/ntopng pull request #8200
Opened 2024-02-01 16:21 UTC by NicoMaio

Fix the similarity in content between the table and chart view by adding the L7 master and app protocol filter.
Fix the empty table view in the case of the view interface.

2024-02-07 15:23 UTC, lucaderi requested changes

2024-02-07 15:23 UTC, lucaderi commented on src/NetworkInterface.cpp
> +  if (filter_vlan_id != (u_int16_t)-1) {
Please #define NO_VLAN (u_int16_t)-1

2024-02-07 15:23 UTC, lucaderi commented on src/NetworkInterface.cpp
> +  ndpi_protocol detected_protocol = f->get_detected_protocol();
Please use integer arithmetics for comparison

2024-02-28 14:01 UTC, NicoMaio commented on src/NetworkInterface.cpp
> +  if (filter_vlan_id != (u_int16_t)-1) {
Fixed by d77d5568d339619566e97dc7302fe609fe36656e

2024-02-28 14:01 UTC, NicoMaio commented on src/NetworkInterface.cpp
> +  ndpi_protocol detected_protocol = f->get_detected_protocol();
Fixed by e52ef99bbbc0fd47be3ae41a14b232e7b3f60ec3

2024-03-06 10:29 UTC, lucaderi commented on include/HostsPortsAnalysis.h
> +        u_int16_t port = 0;
this is a bad practice as you should set values in constructor

2024-03-06 10:30 UTC, merged