Update typeahead script and use ip addresses when searching hosts
ntop/ntopng pull request #836
Opened 2016-11-29 17:11 UTC by emanuele-f

The migration of existing code to avoid hostname-based access to the host_details page should be gradual since it is spread across different scripts in the codebase. This patch only fixes search bars related to #835.

2016-11-30 09:55 UTC, simonemainardi requested changes

2016-11-30 09:55 UTC, simonemainardi commented on scripts/lua/find_host.lua
> +	          if findString(v, ":") == nil then
check lua_utils there are already functions that check if the IP is v4 or v6 and they should also be more accurate

2016-11-30 14:04 UTC, simonemainardi commented on scripts/lua/find_host.lua
> +	 tprint(res)
remove this debug line

2016-11-30 14:08 UTC, simonemainardi approved these changes

2016-11-30 14:09 UTC, simonemainardi commented
thank you @emanuele-f

2016-11-30 14:09 UTC, merged

2016-12-01 08:26 UTC, lucaderi commented
@emanuele-f @simonemainardi This code is bugged and never tested. See " if isIPv6String(v) then" in find_host.lua and you will understand why it doesn't work.