Invalid SYNFlood Error Fix
ntop/ntopng pull request #8747
Opened 2024-10-05 17:35 UTC by YellowMan02

Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines https://github.com/ntop/ntopng/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/src/) to reflect the changes made (if applicable)

Link to the related [issue](https://github.com/ntop/ntopng/issues):

Describe changes:
To determine whether a host is an attacker or a victim of a SYNFlood attack, we can count the difference between the number of established and active TCP flows, as a client and as a server (where established means that the 3wh has been performed correctly and active means that the 3wh has been started but not yet completed).

2024-10-07 12:53 UTC, lucaderi requested changes
Almost working, please fix the issue reported.

2024-10-07 12:53 UTC, lucaderi commented on include/Host.h
> +    std::atomic<u_int32_t> num_active_tcp_flows_as_client, num_established_tcp_flows_as_client; /* (attacker) */
These might not be necessary, we'll removed them if so

2024-10-07 12:53 UTC, lucaderi commented on src/Host.cpp
> +    syn_flood.num_established_tcp_flows_as_server--;
In this method you need to decrease after checking if the counter was previously increased otherwise your lice will break. Please fix it

2024-10-13 09:01 UTC, MatteoBiscosi approved these changes

2024-10-13 09:01 UTC, merged